### ISSUE TITLE
wubi-lex

### ISSUE THREAD

**Issue by liudeing** [aardio/chineseocr_lite_dll#3]
抱歉，那边仓库没有开issue.
替换为五笔98码表后，其实也可以打拼音，但显示出来的编码依然是86版的。相当于五笔拼音混合，打拼音显示码表不对，望改进下。”气“ 显示的还是是rnb

**Comment by aardio** [comment]
wubiLex 有关的问题请反馈到官网链接的帖子,
你说的拼音输入的五笔提示是个鸡肋功能，其实没什么用可以忽略，wubiLex 提供了记忆效果更好的反查图像拆字，按 Ctrl + F2 反查，再按 Ctrl + F2 回到原来位置继续输入。

wubiLex 只能管理码表或者超级热键，并不修改微软五笔的功能，如果你确有此需求，请到微软官网反馈。
